"use client";

import Link from "next/link";
import { useState } from "react";
import { Status } from "@/components/ui";
import { duration, percent } from "@/lib/api";
import type { Run } from "@/lib/types";

export function RunComparison({runs}:{runs:Run[]}){const[selected,setSelected]=useState<string[]>([]);const[comparison,setComparison]=useState<Run[]>([]);const[error,setError]=useState("");const[pending,setPending]=useState(false);function toggle(id:string){setSelected(current=>current.includes(id)?current.filter(value=>value!==id):current.length<4?[...current,id]:current)}async function compare(){setPending(true);setError("");const query=new URLSearchParams();selected.forEach(id=>query.append("ids",id));const response=await fetch(`/api/v1/runs/compare?${query}`);if(!response.ok){setError("Select at least two completed runs.");setPending(false);return}setComparison(await response.json());setPending(false)}return <><section className="panel"><div className="panel-title"><div><span className="eyebrow">Select 2–4 runs</span><h2>Evaluation history</h2></div><button className="primary-button" disabled={selected.length<2||pending} onClick={compare}>{pending?"Comparing…":`Compare ${selected.length||""} runs`}</button></div>{error&&<p className="inline-error" role="alert">{error}</p>}<div className="table-wrap"><table><thead><tr><th><span className="sr-only">Select</span></th><th>Run</th><th>Benchmark / agent</th><th>Status</th><th>Pass@k</th><th>Score</th><th>Duration</th><th>Tokens</th></tr></thead><tbody>{runs.map(run=><tr key={run.id}><td><input aria-label={`Select run ${run.id}`} type="checkbox" checked={selected.includes(run.id)} disabled={!selected.includes(run.id)&&selected.length>=4} onChange={()=>toggle(run.id)}/></td><td><Link className="run-id" href={`/runs/${run.id}`}>RUN-{run.id.slice(0,7).toUpperCase()}</Link><small>{new Date(run.created_at).toLocaleDateString()}</small></td><td><strong>{run.benchmark_name}</strong><small>{run.agent_name} · k={run.attempts}</small></td><td><Status value={run.status}/></td><td>{percent(run.pass_at_k)}</td><td>{run.mean_score.toFixed(2)}</td><td>{duration(run.duration_ms)}</td><td>{run.total_tokens.toLocaleString()}</td></tr>)}</tbody></table></div></section>{comparison.length>0&&<section className="comparison-grid" aria-live="polite">{comparison.map(run=><article key={run.id} className="comparison-card"><span className="eyebrow">RUN-{run.id.slice(0,7).toUpperCase()}</span><h2>{run.agent_name}</h2><p>{run.benchmark_name}</p><dl><div><dt>Pass@k</dt><dd>{percent(run.pass_at_k)}</dd></div><div><dt>Mean score</dt><dd>{run.mean_score.toFixed(2)}</dd></div><div><dt>Duration</dt><dd>{duration(run.duration_ms)}</dd></div><div><dt>Tokens</dt><dd>{run.total_tokens.toLocaleString()}</dd></div></dl><Link className="ghost-button" href={`/runs/${run.id}`}>Inspect run</Link></article>)}</section>}</>}
